config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "/groupworkshops", to: "group_workshops#index"
  get "/groupworkshops/:id/:part", to: "group_workshops#show", as: "group"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/group_workshops_controller.rb
class GroupWorkshopsController < ApplicationController
    def index
    end 
    
    def show  
        @part = params[:part]
        @prev_part = @part.to_i - 1
        @next_part = @part.to_i + 1
        @workshop = params[:id]
        if @workshop.to_i == 1
            render "learning_basics"
        end
        if @workshop.to_i == 2
            render "explore_challenges"
        end
        if @workshop.to_i == 3
            render "practice_implementation"
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/group_workshops/_timer.html.erb
<div class="timer" data-timer-target="timer" data-controller="timer">
    <p><span data-timer-target="minutes" class="timer-content"><%= start_min %></span>
    <span class="timer-content divider">:</span>
    <span data-timer-target="seconds" class="timer-content">00</span></p>
    <button type="button" data-timer-target="startButton" data-action="click->timer#control"><i class="fa-solid fa-play"></i></button>
</div>

app/views/group_workshops/_wsh1_part_1.html.erb
<div class="champ-block">
    <div class="page-content">
        <h1>Welcome!</h1>
        <p>We're glad you're here for our online workshop for general practitioners on applying strategies from motivational interviewing to help patients modify their behaviour. The goal of this training is to give GPs the skills and information they need to effectively employ motivational interviewing strategies to help their patients modify their behaviour.</p>
        <p>During this workshop, participants will not only learn about the principles and techniques of Motivational Interviewing, but also about the stages of change, the link between motivation and health literacy, and the two essential components of motivation. We will delve into how to place a high sense of importance or value in changing an aspect of behavior and how to build self-efficacy or confidence in one's ability to change. With this knowledge, GPs can tailor their approach to best suit the patient's needs, increase the likelihood of success, and reduce the risk of relapse.</p>
        <p>By the end of this workshop, participants will have a deeper understanding of how to use Motivational Interviewing in their practice to help patients achieve their health goals. We look forward to sharing our expertise with you and helping you enhance your skills as a GP.</p>
    </div>

    <div class="champ-col">
        <%# <%= render partial: 'pages/champion', locals: { instructions: "Hi, I am your virtual workshop guide. This workshop is designed to be completed on a laptop or desktop computer. For a successful workshop, please gather a group of doctors who will participate in the workshop together and choose one person to be the champion of the workshop, or leader. This person will be responsible for guiding the group through the workshop IRL and ensuring that everyone stays on track." } %>
        <div class="champion">
            <%= image_tag "champion.png", alt: "champion logo", class:"champion-logo"%>
            <div class="champion-note">
                <div data-controller="audio">
                    <i class="fa-solid fa-volume-high" data-action="click->audio#play" data-audio-target="iconPlay"></i>
                    <i class="fa-solid fa-volume-xmark d-none" data-action="click->audio#pause" data-audio-target="iconPause"></i>
                    <audio hidden data-audio-target="audioFile">
                        <source src="<%= asset_path('wsh01-welcome01.mp3') %>" >
                        Your browser does not support the audio element.
                    </audio>
                </div>
                
                <p>Hi, I am your virtual workshop guide. This workshop is designed to be completed on a laptop or desktop computer. For a successful workshop, please gather a group of doctors who will participate in the workshop together and choose one person to be the champion of the workshop, or leader. This person will be responsible for guiding the group through the workshop IRL and ensuring that everyone stays on track</p>
            </div>
        </div>
    </div>  
</div>
<div class="navigation-buttons">
    <%= link_to "Back", groupworkshops_path, class: "button button-orange" %>
    <%= link_to "Next", group_path(@workshop, @next_part), class: "button button-orange" %>
</div>

app/views/group_workshops/_wsh1_part_4.html.erb
<div class="champ-block">
    <div class="page-content">
        <h2>Motivational Interviewing (MI)</h2>

        <p>During the contemplation and preparation stages, patients experience an intention-action gap, which refers to the disparity between their intention or desire to change a behavior and their actual ability or readiness to take action towards that change. This gap highlights the challenge individuals face when expressing willingness to change, yet encountering barriers that hinder them from translating their intentions into concrete actions.</p>

        <p>Motivational Interviewing (MI) is a <span>patient-centered</span> approach that can be instrumental in addressing the intention-action gap during the contemplation and preparation stages of behavior change. </p>

        <p>Please watch the video below, where you'll hear from Katrina Anderson, an experienced health professional, as she shares her valuable experience with patients and her unique perspective on MI.</p>

        <iframe width="1000" height="315" src="https://www.youtube.com/embed/RKEeRqLtKqo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

        <p>As you have seen in the video, MI can be likened to a GP planting seeds of change in the fertile soil of a patient's mind, with the hope that some of these seeds will eventually take root and flourish. MI nurtures the growth of motivation and facilitates positive behavioral changes. By understanding the essence of MI, GPs can effectively use this approach in their consultations to support patients' health behavior transformations.</p>

        <p>Just as a gardener carefully tends to their plants, GPs employing MI engage in a thoughtful and collaborative process with their patients. Here are some ways GPs can utilize MI, using the seed analogy:</p>

        <div class="row">
            <div class="col card-oars">
                <%= image_tag("oars-o.PNG") %>
                <div class="oars-content">
                    <h3>CULTIVATING THE SOIL</h3>
                    <p>GPs can begin by creating an environment that promotes <span>O</span>pen exploration and understanding. By asking open-ended questions, they gently prepare the soil for the patient to reflect and share their concerns, motivations, and desires for change.</p>
                </div>
                <div class="example">
                    <p>"What are your thoughts on making a change in your health behavior?"</p>
                </div>
            </div>

            <div class="col card-oars">
                <%= image_tag("oars-r.PNG") %>
                <div class="oars-content">
                    <h3>PLANTING THE SEEDS</h3>
                    <p><span>R</span>eflective listening is akin to planting the seeds of change. GPs can attentively listen to their patients, capturing their words and emotions, and then mirror them back. This allows the patient to witness their own thoughts and encourages a deeper examination of their ambivalence.</p>
                </div>
                <div class="example">
                    <p>"It sounds like you have mixed feelings about making this change."</p>
                </div>
            </div>
            <div class="col m-3 card-oars">
                <%= image_tag("oars-a.PNG") %>
                <div class="oars-content">
                    <h3>NURTURING GROWTH</h3>
                    <p><span>A</span>ffirmations act as nourishment for the growing seeds. These positive acknowledgments cultivate the patient's self-confidence, validating their efforts and strengths along the way.</p>
                </div>
                <div class="example">
                    <p>"I appreciate your willingness to discuss this with me."</p>
                </div>
            </div>
            <div class="col m-3 card-oars">
                <%= image_tag("oars-s.PNG") %>
                <div class="oars-content">
                    <h3>CHECKING PROGRESS</h3>
                    <p><span>S</span>ummarizing is akin to checking on the progress of the growing seeds. GPs can periodically summarize the patient's journey. This helps the patient see their progress, providing clarity and fostering a sense of accomplishment.</p>
                </div>
                <div class="example">
                    <p>"Let me make sure I understand what you've shared so far."</p>
                </div>
            </div>
        </div>

        <p>These four steps align with a well-known acronym that represents key communication techniques in Motivational Interviewing - <span>OARS</span>.</p>
        <%= image_tag("oars.PNG", class: "menu_icon img_300_size") %>

        <p>By incorporating these OARS techniques into their conversations, GPs can create a fertile ground for meaningful discussions, enabling patients to explore their motivations and make positive behavior changes. The cultivation of open-ended questions, the sowing of affirmations, the nurturing of reflective listening, and the periodic checking of progress through summarizing all contribute to the growth and development of collaborative and patient-centered consultations.</p>


        <%# MI quiz %>
        <%= render partial: "mi_quiz" %>
    </div>

    <div class="champ-col">
        
    </div>  
</div>
<div class="navigation-buttons">
    <%= link_to "Back", group_path(@workshop, @prev_part), class: "button button-orange" %>
    <%= link_to "Next", group_path(@workshop, @next_part), class: "button button-orange" %>
</div>

app/views/group_workshops/_wsh1_part_5.html.erb
<div class="champ-block">
    <div class="page-content">
        <h2>Activity: "Observe the language"</h2>

        <p>The significance of language in communication is paramount for patient engagement and behavior change. By employing Motivational Interviewing techniques, such as OARS, health professionals can nurture a patient-centered approach, fostering trust and collaboration in their consultations to achieve positive and meaningful health outcomes.</p>

        <p>In this activity, we will have a group discussion where one volunteer presents their patient's notes, and together, we will explore ways to improve our consultation approach by focusing on language usage. The goal is to collaboratively identify areas for improvement and generate ideas for more effective future consultations with that patient.</p>

        <p>Please select one volunteer to share the patient's notes, focusing on key interactions and the language used during the consultation. The volunteer can also provide context, including the patient's concerns, goals, and any challenges encountered during the conversation. This will help us analyze and discuss specific instances where language played a crucial role in the consultation process.</p>

        <p>As the champion, encourage the group to actively participate and share their perspectives, drawing from their own experiences and knowledge of MI and OARS techniques. Facilitate a constructive dialogue where participants provide suggestions, examples, and insights on improving language use and enhancing patient-centered care. Additionally, as the champion, feel free to invite participants to ask their own questions based on their professional experience or use any of the provided ones to facilitate the discussion:</p>

        <ol>
            <li>What language did you notice being used during the consultation?</li>
            <li>Were there any specific phrases or responses that stood out to you?</li>
            <li>Considering MI and OARS techniques, what could have been done differently to enhance the conversation?</li>
            <li>How might alternative language choices have impacted the patient's engagement and motivation for behavior change?</li>
            <li>Based on what we've discussed, what specific strategies or questions could be used in future consultations with this patient to elicit change talk and enhance collaboration?</li>
        </ol>
  </div>

    <div class="champ-col">
        
    </div>  
</div>
<div class="navigation-buttons">
    <%= link_to "Back", group_path(@workshop, @prev_part), class: "button button-orange" %>
    <%= link_to "Next", group_path(@workshop, @next_part), class: "button button-orange" %>
</div>

app/views/group_workshops/_wsh1_part_6.html.erb
<div class="champ-block">
    <div class="page-content">
         <%# MOTIVATION %>
        <h2>Motivation</h2>

        <p>Motivation is an essential aspect of patients' behavior change, and as health professionals, we often encounter the challenge of evoking motivation in our patients. However, misconceptions surrounding motivation can sometimes leave us feeling helpless in supporting them effectively.</p>

        <p>It is commonly believed that motivation is solely synonymous with excitement, high energy, or joy. While these feelings may accompany high motivation for some, for others it is not the case. Understanding the true essence of motivation is crucial in empowering patients to embark on their journey of change.</p>

        <p>Join us as we hear from Professor Liz Rieger, a distinguished clinical psychologist and researcher at The Australian National University. In this insightful video, Professor Rieger unravels the complexity of motivation, defining its cognitive nature and exploring the two fundamental components that drive behavior change.</p>

        <iframe width="1000" height="315" src="https://www.youtube.com/embed/7nc0XY8XOsU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

        <%# HEALTH LITERACY %>
        <h2>Motivation and health literacy</h2>

        <p>The foundation of high-quality healthcare is effective communication, and patient outcomes are significantly influenced by <span>health literacy</span>. Systemic inequalities can substantially impact patients' health literacy, creating obstacles to understanding and obtaining crucial health information. Disparities in health outcomes may result from this, and patients may find it difficult to make well-informed choices regarding their care and communicate their confusion during consultations. Such behavious can often be misinterpreted as a lack of motivation to follow through with prescribed plans. </p>

        <p>It could be challenging for highly educated health practitioners to relate to people with low health literacy. Healthcare practitioners, however, can modify their communication techniques and provide personalised assistance by respecting the varied backgrounds and experiences of their patients. This eventually empowers people to take responsibility for their health journeys with confidence and understanding.</p>

        <p>Consider a patient who is given a customised meal plan to manage chronic disease and enhance overall health. You outline the suggested diet, highlighting the value of balanced meals, portion control, and healthy food selections. The patient nods in agreement throughout the consultation, but they don't appear to significantly alter their behaviour the following consultations. Are they not motivated, or do you have any indications they might not understand your treatment plan?</p>

        <p>To address this situation, the healthcare professional can utilise <span>the "teach-back" method</span>. You can ask the patient to describe the diet plan's main elements in their own words after you've explained it to them. For example, you might ask,<span class="example-response"> "Can you tell me how you plan to incorporate balanced meals into your daily routine?"</span></p>

        <p>Through the patient's response, the healthcare provider can identify any misunderstandings and offer further guidance. You might discuss portion sizes, suggest meal ideas, and explore strategies for overcoming potential obstacles to adhering to the diet plan.</p>

        <p>By employing the "teach-back" method, patients gain a clearer understanding of their medical plan, fostering a sense of importance in adhering to it for better health outcomes. Moreover, as patients develop confidence in their ability to make informed medical choices, they are more likely to take meaningful action towards sustaining their behaviour change. The "teach-back" method creates a powerful synergy that enhances patient engagement and sets them on a path to successful behavior change.</p>
    </div>

    <div class="champ-col">
        
    </div>  
</div>
<div class="navigation-buttons">
    <%= link_to "Back", group_path(@workshop, @prev_part), class: "button button-orange" %>
    <%= link_to "Next", group_path(@workshop, @next_part), class: "button button-orange" %>
</div>

app/views/group_workshops/_wsh2_part_1.html.erb
<div class="champ-block">
    <div class="page-content">
        <h1>Welcome!</h1>
        <p>Welcome to the second part of our series of workshops designed to dive into the intricacies of behaviour change in patient care.</p>
        <p>You frequently see patients struggling with the challenges of behaviour modification in your regular clinical work. We cordially encourage you to examine the difficulties of your patients' journey to better lifestyles and your own as healthcare professionals present today.</p>
        <p>Our goal is to establish a welcoming environment where you can freely exchange experiences, identify related problems, and come up with potential solutions within your practice.</p>
        <p>In order to overcome the challenges that frequently hide in the shadows—such as understanding patient motivations, resolving health literacy gaps, or appreciating the richness of cultural diversity—we ask that you all work together to shed light on them.</p>
        <p>The goal of the workshop today is to find useful tactics that will enable you to support your patients' attempts at positive behaviour change more effectively.</p>
        <p>So let's set out on this exploration together, equipped with our combined knowledge and a shared desire to improve patient care. We can improve the lives of individuals we serve by discovering the secrets of enduring behaviour change together. Start your exploration now!</p>
        <p>This workshop is designed to last an hour, and there are no prerequisites to start — your unique experiences and insights are all that's required. However, access to a whiteboard or digital platform would be advantageous.</p>
    </div>
</div>
<div class="navigation-buttons">
    <%= link_to "Back", groupworkshops_path, class: "button button-orange" %>
    <%= link_to "Next", group_path(@workshop, @next_part), class: "button button-orange" %>
</div>

app/views/group_workshops/_wsh2_part_2.html.erb
<div class="champ-block">
    <div class="page-content">
        <h1>Activity: Exploring the challenges</h1>

        <p>Please nominate a champion, a seasoned professional, who will navigate through our discussion and ensure a productive exploration.</p>
        <div class="activity-cards">
            <ul>
                <li class="activity-card">
                    <div class="activity-card__content">
                        <div class="activity-card__text">
                            <h1>Sharing Experiences</h1>
                            <p>Invite participants to take turns sharing their experiences with behavior change in patients. Each participant should have 2-3 minutes to discuss a specific patient case or scenario.</p>
                            <p>Champion will keep track of key challenges mentioned.</p>
                            <p>Encourage participants to highlight challenges they encountered that seemed particularly hard.</p>
                        </div>
                        <div class="activity-card__timer">
                            <%= render partial: 'timer', locals: { start_min: 15.to_s.rjust(2,'0') } %>
                        </div>
                    </div>
                </li>
                <li class="activity-card">
                    <div class="activity-card__content">
                        <div class="activity-card__text">
                            <h1>Identifying Common Challenges</h1>
                            <p>Based on the shared experiences, guide a discussion to identify common challenges faced by healthcare professionals in supporting behaviour change.</p>
                            <p>Champion should facilitate the discussion by asking open-ended questions and encouraging participants to share their insights.</p>
                            <p>Create a list of common challenges on a whiteboard or digital platform.</p>
                        </div>
                        <div class="activity-card__timer">
                            <%= render partial: 'timer', locals: { start_min: 10.to_s.rjust(2,'0') } %>
                        </div>
                    </div>
                </li>
            </ul>
        </div>

        <p>Please keep the list of challenges accessible throughout the duration of the workshop as we will address it continiously.</p>
    </div>
</div>
<div class="navigation-buttons">
<%= link_to "Back", group_path(@workshop, @prev_part), class: "button button-orange" %>
<%= link_to "Next", group_path(@workshop, @next_part), class: "button button-orange" %>
</div>

app/views/group_workshops/_wsh2_part_3.html.erb
<div class="page-content">
    <h1>Brief conversations in practice</h1>

    <p>You've collectively recognised a few hurdles that you often face in your line of work. One common challenge that resonates with many health professionals is the relentless ticking of the clock during patient consultations. The pressures of short appointment slots can leave health professionals wondering how to tackle the depth of their patients' health needs effectively.</p>
    <p>But, worry not, because in this part of our workshop, we're diving into practical strategies that can help us navigate these time constraints like true pros. We'll uncover how to plant those all-important "seeds" of change, as we discussed in our previous session, even within the confines of a quick chat.</p>
    <p>To start off the discussion, please watch the video below. In this video, a GP grapples with a short consultation time while raising an important discussion about a patient's weight management. This video serves as a ripper illustration of how, even in the shortest of exchanges, we can sow the seeds of change, nurturing the potential for future progress.</p>

    <iframe width="100%" height="500" src="https://www.youtube.com/embed/bTRRNWrwRCo?si=ZNXLcLul0AsIS6_U&amp;start=30" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

    <div class="activity-cards">
        <ul>
            <li class="activity-card">
                <div class="activity-card__content">
                    <div class="activity-card__text">
                        <h1>Initial thoughts</h1>
                        <p>In a group, please share your initial impressions and thoughts about the GP's approach. Consider the effectiveness of the GP's communication and any positive aspects you have observed.</p>
                    </div>
                    <div class="activity-card__timer">
                        <%= render partial: 'timer', locals: { start_min: 5.to_s.rjust(2,'0') } %>
                    </div>
                </div>
            </li>
            <li class="activity-card">
                <div class="activity-card__content">
                    <div class="activity-card__text">
                        <h1>Reflecting on the time constraints</h1>
                        <p>Transition to a discussion of the challenges and limitations faced by the GP in this brief consultation. In a group, identify specific barriers related to time constraints and the patient's pre-contemplative stage.</p>
                    </div>
                    <div class="activity-card__timer">
                        <%= render partial: 'timer', locals: { start_min: 5.to_s.rjust(2,'0') } %>
                    </div>
                </div>
            </li>
            <li class="activity-card">
                <div class="activity-card__content">
                    <div class="activity-card__text">
                        <h1>Brainstorming ideas</h1>
                        <p>Please share your own experiences or tactics you have used to address similar challenges in your practice.</p>
                    </div>
                    <div class="activity-card__timer">
                        <%= render partial: 'timer', locals: { start_min: 5.to_s.rjust(2,'0') } %>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>
<div class="navigation-buttons">
    <%= link_to "Back", group_path(@workshop, @prev_part), class: "button button-orange" %>
    <%= link_to "Next", group_path(@workshop, @next_part), class: "button button-orange" %>
</div>

app/views/group_workshops/_wsh2_part_5.html.erb
<div class="champ-block">
    <div class="page-content">
        <h1>Activity: Brainstorming Solutions</h1>

        <div class="activity-cards">
            <ul>
                <li class="activity-card">
                    <div class="activity-card__content">
                        <div class="activity-card__text">
                            <h1>Brainstorming Solutions</h1>
                            <p>Transition to a brainstorming session where participants collectively suggest strategies and solutions to address the challenges identified in the beginning of the workshop.</p>
                            <p>Champion should guide the brainstorming process and ensure that a diverse range of ideas is considered.</p>
                            <p>Document the suggested solutions alongside the list of challenges.</p>
                        </div>
                        <div class="activity-card__timer">
                            <%= render partial: 'timer', locals: { start_min: 15.to_s.rjust(2,'0') } %>
                        </div>
                    </div>
                </li>
                <li class="activity-card">
                    <div class="activity-card__content">
                        <div class="activity-card__text">
                            <h1>Group Discussion</h1>
                            <p>Open the floor for a group discussion where participants can ask questions, seek clarification, and provide additional insights.</p>
                            <p>Encourage participants to share their thoughts on the feasibility and effectiveness of the suggested solutions.</p>
                            <p>Champion should moderate the discussion to keep it focused and constructive.</p>
                        </div>
                        <div class="activity-card__timer">
                            <%= render partial: 'timer', locals: { start_min: 10.to_s.rjust(2,'0') } %>
                        </div>
                    </div>
                </li>
                <li class="activity-card">
                    <div class="activity-card__content">
                        <div class="activity-card__text">
                            <h1>Action Plan</h1>
                            <p>Summarize the key challenges and potential solutions discussed during the workshop.</p>
                            <p>Discuss the importance of implementing these solutions in participants' healthcare practices.</p>
                            <p>Invite participants to consider how they can incorporate these strategies into their patient interactions.</p>
                        </div>
                        <div class="activity-card__timer">
                            <%= render partial: 'timer', locals: { start_min: 5.to_s.rjust(2,'0') } %>
                        </div>
                    </div>
                </li>
            </ul>
        </div>

    </div>
</div>
<div class="navigation-buttons">
    <%= link_to "Back", group_path(@workshop, @prev_part), class: "button button-orange" %>
    <%= link_to "Finish the Workshop", groupworkshops_path, class: "button button-orange" %>
</div>

app/views/group_workshops/explore_challenges.html.erb
   <%# Side-bar menu %>
<div class="workshop-page-outline">
    <div class="workshop-menu" data-controller="wsh-menu">
        <div class="course-list">
            <h3>EXPLORE CHALLENGES</h3>
            <ul data-wsh-menu-target="list">
                <li><a href="<%= group_path(2,1) %>"><div class="list-item"><p>Welcome</p><p>5 min</p></div></a></li>
                <li><a href="<%= group_path(2,2) %>"><div class="list-item"><p>Activity: Exploring challenges</p><p>25 min</p></div></a></li>
                <li><a href="<%= group_path(2,3) %>"><div class="list-item"><p>Brief conversations in practice</p><p>25 min</p></div></a></li>
                <li><a href="<%= group_path(2,4) %>"><div class="list-item"><p>MI for pre-contemplative patients</p><p>15 min</p></div></a></li>
                <li><a href="<%= group_path(2,5) %>"><div class="list-item"><p>Activity: Brainstorming Solutions</p><p>15 min</p></div></a></li>
            </ul>
        </div>
        <div class="menu-toggle" data-wsh-menu-target="menuButton" data-action="click->wsh-menu#open" >
            <i class="fa-solid fa-chevron-right"></i>
        </div>
    </div>

    
    <%# Page content %>
    <div class="container-lg my-3">
        <%= render partial: "wsh2_part_#{@part}" %>
    </div>
</div>

app/views/pages/_champion.html.erb
<div class="champion">
    <%= image_tag "champion.png", alt: "champion logo", class:"champion-logo"%>
    <div class="champion-note">
        <p><%= instructions %></p>
    </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to image_tag("Change-Talk-logo-line.png"), root_path, class: "navbar-brand" %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active"><a class="nav-link" href="#">About</a></li>
          <li class="nav-item"><%= link_to "Workshops", groupworkshops_path, class: "nav-link" %></li>
          <li class="nav-item"><a class="nav-link" href="#">Blog</a></li>
          <li class="nav-item"><a class="nav-link" href="#">Download Resources</a></li>
          <li class="nav-item"><a class="nav-link" href="#">Contact</a></li>
      </ul>
    </div>
  </div>
</div>